version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: homestead
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersecret
    ports:
      - 27017:27017
