version: '3'

services:
  app:
    build:
      context: ../.
      dockerfile: ./build/app/Dockerfile
    environment:
      WAIT_HOSTS: mongo:27017
    depends_on: 
      - mongo 
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
